In [1]:
import torch
import torch.nn as nn
import numpy as np
import joblib
from torch_geometric.data import Data

In [2]:
patient_and_stage = joblib.load("esca_patients_and_stage.pkl")

In [3]:
len(patient_and_stage)

135

In [4]:
patient_and_stage

{'TCGA-L5-A4OR': 'Stage IA',
 'TCGA-IG-A3YA': 'Stage IIIA',
 'TCGA-JY-A93D': 'Stage IIIC',
 'TCGA-LN-A7HX': 'Stage IIA',
 'TCGA-JY-A6FE': 'Stage III',
 'TCGA-JY-A93F': 'Stage IB',
 'TCGA-Z6-A9VB': 'Stage IIIA',
 'TCGA-LN-A49Y': 'Stage IIA',
 'TCGA-S8-A6BV': 'Stage IIIA',
 'TCGA-VR-A8ET': 'Stage IIA',
 'TCGA-L5-A4OF': 'Stage IIB',
 'TCGA-V5-AASV': 'Stage IIB',
 'TCGA-LN-A49R': 'Stage III',
 'TCGA-2H-A9GQ': 'Stage III',
 'TCGA-LN-A49W': 'Stage III',
 'TCGA-Z6-AAPN': 'Stage IIA',
 'TCGA-L5-A4OX': 'Stage IIB',
 'TCGA-LN-A4MR': 'Stage IIA',
 'TCGA-Q9-A6FU': 'Stage IIIB',
 'TCGA-L5-A4OW': 'Stage IIB',
 'TCGA-VR-A8EY': 'Stage IIA',
 'TCGA-JY-A6FA': 'Stage IIB',
 'TCGA-L5-A4OQ': 'Stage IIIA',
 'TCGA-LN-A9FQ': 'Stage IIA',
 'TCGA-2H-A9GM': 'Stage IIB',
 'TCGA-XP-A8T6': 'Stage IIB',
 'TCGA-IG-A6QS': 'Stage IIB',
 'TCGA-LN-A5U7': 'Stage IIA',
 'TCGA-XP-A8T8': 'Stage IIB',
 'TCGA-VR-A8EU': 'Stage IV',
 'TCGA-JY-A93C': 'Stage IIIB',
 'TCGA-LN-A49O': 'Stage IIA',
 'TCGA-L5-A4OI': 'Stage IIIC',
 'TCG

In [5]:
tmp_stage = []
for x in patient_and_stage:
    tmp_stage.append(patient_and_stage[x])
print(set(tmp_stage))

{'Stage IIIB', 'Stage IIIC', 'Stage IIA', 'Stage IV', 'Stage IB', 'Stage IVA', 'Stage III', 'Stage I', 'Stage IIB', 'Stage IA', 'Stage II', 'Stage IIIA'}


In [6]:
patient_and_label = {}
for x in patient_and_stage:
    if patient_and_stage[x] in ['Stage III', 'Stage IIIB', 'Stage IIIC', 'Stage IV', 'Stage IVA', 'Stage IIIA']:
        patient_and_label[x] = 1
    elif patient_and_stage[x] in [ 'Stage IIB', 'Stage IA', 'Stage IB', 'Stage II', 'Stage I', 'Stage IIA']:
        patient_and_label[x] = 0

In [7]:
patient_and_label

{'TCGA-L5-A4OR': 0,
 'TCGA-IG-A3YA': 1,
 'TCGA-JY-A93D': 1,
 'TCGA-LN-A7HX': 0,
 'TCGA-JY-A6FE': 1,
 'TCGA-JY-A93F': 0,
 'TCGA-Z6-A9VB': 1,
 'TCGA-LN-A49Y': 0,
 'TCGA-S8-A6BV': 1,
 'TCGA-VR-A8ET': 0,
 'TCGA-L5-A4OF': 0,
 'TCGA-V5-AASV': 0,
 'TCGA-LN-A49R': 1,
 'TCGA-2H-A9GQ': 1,
 'TCGA-LN-A49W': 1,
 'TCGA-Z6-AAPN': 0,
 'TCGA-L5-A4OX': 0,
 'TCGA-LN-A4MR': 0,
 'TCGA-Q9-A6FU': 1,
 'TCGA-L5-A4OW': 0,
 'TCGA-VR-A8EY': 0,
 'TCGA-JY-A6FA': 0,
 'TCGA-L5-A4OQ': 1,
 'TCGA-LN-A9FQ': 0,
 'TCGA-2H-A9GM': 0,
 'TCGA-XP-A8T6': 0,
 'TCGA-IG-A6QS': 0,
 'TCGA-LN-A5U7': 0,
 'TCGA-XP-A8T8': 0,
 'TCGA-VR-A8EU': 1,
 'TCGA-JY-A93C': 1,
 'TCGA-LN-A49O': 0,
 'TCGA-L5-A4OI': 1,
 'TCGA-2H-A9GG': 1,
 'TCGA-IG-A3I8': 0,
 'TCGA-LN-A4A5': 0,
 'TCGA-VR-AA7B': 1,
 'TCGA-VR-AA7I': 1,
 'TCGA-2H-A9GO': 1,
 'TCGA-ZR-A9CJ': 1,
 'TCGA-LN-A49S': 0,
 'TCGA-LN-A4MQ': 1,
 'TCGA-IG-A4QT': 0,
 'TCGA-LN-A4A8': 0,
 'TCGA-JY-A6FH': 0,
 'TCGA-JY-A6FD': 0,
 'TCGA-L5-A4OP': 0,
 'TCGA-IG-A97I': 0,
 'TCGA-VR-AA4D': 0,
 'TCGA-2H-A9GL': 1,


In [8]:
patients = []
for x in patient_and_label:
    patients.append(x)

In [9]:
no_sort_t_all_feature = joblib.load("esca_5x10x_kimianet_patch.pkl")

In [10]:
#pretrain feature
no_sort_t_all_feature['TCGA-LN-A4MR']

{'30-26.png': array([ 0.11480963,  0.15030876,  0.15438452, ..., -0.3086485 ,
         2.0952566 ,  1.0193117 ], dtype=float32),
 '11-7.png': array([ 0.1080293 ,  0.15179563,  0.07385209, ..., -1.3634593 ,
         2.536687  ,  0.41749474], dtype=float32),
 '10-7.png': array([0.10689963, 0.1407605 , 0.10619869, ..., 1.1879535 , 1.0583618 ,
        0.64268196], dtype=float32),
 '16-14.png': array([0.06667145, 0.20699134, 0.06782376, ..., 0.7713442 , 1.8904296 ,
        0.87929785], dtype=float32),
 '17-18.png': array([ 0.10338639,  0.05712068,  0.08759267, ...,  0.7670408 ,
         1.5598419 , -0.02399221], dtype=float32),
 '28-26.png': array([0.04752501, 0.21768577, 0.12455579, ..., 0.08368838, 2.2646322 ,
        0.9284016 ], dtype=float32),
 '31-21.png': array([ 0.11103493,  0.11757961,  0.12441051, ...,  2.050562  ,
         2.599822  , -0.0291452 ], dtype=float32),
 '20-17.png': array([ 0.11338584,  0.11440863,  0.10419206, ...,  0.93217367,
         0.1501774 , -0.16703004], dtyp

In [11]:
t_all_feature = {}
for x in patients:
    feature = {}
    for z in no_sort_t_all_feature[x]:
        if z == '-1':
            feature[z] = no_sort_t_all_feature[x][z]
            
    for z in no_sort_t_all_feature[x]:            
        if len(z.split('-')) == 6:
            feature[z] = no_sort_t_all_feature[x][z]
        
    for z in no_sort_t_all_feature[x]:            
        if len(z.split('-')) == 2 and z != '-1':
            feature[z] = no_sort_t_all_feature[x][z]
        
    t_all_feature[x] = feature


In [12]:
"""
Thumbnail:"-1"
5x:"x1-x2-y1-y2-x-y",x/y are the coordinates of the 5x node, and x1/x2/y1/y2 are the coordinates of the corresponding 10x node
10x:"x-y"
"""
t_all_feature['TCGA-LN-A4MR']

{'-1': array([ 0.03040453,  0.26700664,  0.07548372, ..., -0.4094244 ,
         0.886226  ,  1.8047752 ], dtype=float32),
 '34-35-28-29-17-14.png': array([0.06940576, 0.23001698, 0.16695607, ..., 0.5770061 , 2.1174974 ,
        0.1034441 ], dtype=float32),
 '2-3-6-7-1-3.png': array([ 0.08397469,  0.17341468, -0.10069387, ...,  0.6422272 ,
         2.5842233 , -1.0786229 ], dtype=float32),
 '28-29-26-27-14-13.png': array([ 0.06828591,  0.23206148,  0.12968677, ...,  1.4263378 ,
         1.6484534 , -0.05423415], dtype=float32),
 '16-17-16-17-8-8.png': array([ 0.09137766,  0.14499718,  0.04132989, ...,  0.58380806,
         0.5065441 , -1.2403352 ], dtype=float32),
 '6-7-4-5-3-2.png': array([ 0.08732527,  0.17489187,  0.05356508, ..., -0.22737114,
         2.0591755 , -0.0220786 ], dtype=float32),
 '18-19-12-13-9-6.png': array([ 0.07960034,  0.182362  ,  0.01785599, ...,  0.01531535,
         1.3469121 , -0.67215633], dtype=float32),
 '28-29-20-21-14-10.png': array([ 0.0855515 ,  0.14988

In [13]:
all_feature = {}
for x in patients:
    feature = []
    for z in t_all_feature[x]:
        if z == '-1':
            feature.append(t_all_feature[x][z])
    for z in t_all_feature[x]:            
        if len(z.split('-')) == 6:
            feature.append(t_all_feature[x][z])
    for z in t_all_feature[x]:            
        if len(z.split('-')) == 2 and z != '-1':
            feature.append(t_all_feature[x][z])
        
    all_feature[x] = feature


In [14]:
all_feature['TCGA-LN-A4MR']

[array([ 0.03040453,  0.26700664,  0.07548372, ..., -0.4094244 ,
         0.886226  ,  1.8047752 ], dtype=float32),
 array([0.06940576, 0.23001698, 0.16695607, ..., 0.5770061 , 2.1174974 ,
        0.1034441 ], dtype=float32),
 array([ 0.08397469,  0.17341468, -0.10069387, ...,  0.6422272 ,
         2.5842233 , -1.0786229 ], dtype=float32),
 array([ 0.06828591,  0.23206148,  0.12968677, ...,  1.4263378 ,
         1.6484534 , -0.05423415], dtype=float32),
 array([ 0.09137766,  0.14499718,  0.04132989, ...,  0.58380806,
         0.5065441 , -1.2403352 ], dtype=float32),
 array([ 0.08732527,  0.17489187,  0.05356508, ..., -0.22737114,
         2.0591755 , -0.0220786 ], dtype=float32),
 array([ 0.07960034,  0.182362  ,  0.01785599, ...,  0.01531535,
         1.3469121 , -0.67215633], dtype=float32),
 array([ 0.0855515 ,  0.1498874 ,  0.09744611, ...,  0.31181872,
         1.2870364 , -0.97012794], dtype=float32),
 array([0.03486596, 0.29940772, 0.1388103 , ..., 0.47308838, 1.416357  ,
     

In [15]:

def get_edge_index_2(id):  
    
    start = []
    end = []
    
    patch_id = {}
    i=0
    for x in t_all_feature[id]:
        patch_id[x.split('.')[0]] = i
        i+=1
#     print(patch_id)

    # Edges between nodes of different resolutions
    for x in patch_id:
        if len(x.split('-'))==6:
            start.append(patch_id[x])
            end.append(patch_id['-1'])
            end.append(patch_id[x])
            start.append(patch_id['-1']) 
            
            if x.split('-')[0]+'-'+x.split('-')[2] in patch_id:
                start.append(patch_id[x])
                end.append(patch_id[x.split('-')[0]+'-'+x.split('-')[2]])
                end.append(patch_id[x])
                start.append(patch_id[x.split('-')[0]+'-'+x.split('-')[2]])                
            if x.split('-')[1]+'-'+x.split('-')[2] in patch_id:                
                start.append(patch_id[x])
                end.append(patch_id[x.split('-')[1]+'-'+x.split('-')[2]]) 
                end.append(patch_id[x])
                start.append(patch_id[x.split('-')[1]+'-'+x.split('-')[2]])             
            if x.split('-')[0]+'-'+x.split('-')[3] in patch_id:            
                start.append(patch_id[x])
                end.append(patch_id[x.split('-')[0]+'-'+x.split('-')[3]])
                end.append(patch_id[x])
                start.append(patch_id[x.split('-')[0]+'-'+x.split('-')[3]])            
            if x.split('-')[1]+'-'+x.split('-')[3] in patch_id:            
                start.append(patch_id[x])
                end.append(patch_id[x.split('-')[1]+'-'+x.split('-')[3]])
                end.append(patch_id[x])
                start.append(patch_id[x.split('-')[1]+'-'+x.split('-')[3]]) 


        
    patch_id_5x = {}
    for x in patch_id:
        if len(x.split('-'))==6:
            patch_id_5x[x.split('-')[-2]+'-'+x.split('-')[-1]] = patch_id[x]
#     print(patch_id_5x)

    #5x resolution edge between nodes
    for x in patch_id:
        if len(x.split('-'))==6:
            i = int(x.split('-')[-2])
            j = int(x.split('-')[-1])
#             print(i,j)
            if str(i)+'-'+str(j+1) in patch_id_5x:
                start.append(patch_id_5x[str(i)+'-'+str(j)])
                end.append(patch_id_5x[str(i)+'-'+str(j+1)])
            if str(i)+'-'+str(j-1) in patch_id_5x:
                start.append(patch_id_5x[str(i)+'-'+str(j)])
                end.append(patch_id_5x[str(i)+'-'+str(j-1)])
            if str(i+1)+'-'+str(j) in patch_id_5x:
                start.append(patch_id_5x[str(i)+'-'+str(j)])
                end.append(patch_id_5x[str(i+1)+'-'+str(j)])
            if str(i-1)+'-'+str(j) in patch_id_5x:
                start.append(patch_id_5x[str(i)+'-'+str(j)])
                end.append(patch_id_5x[str(i-1)+'-'+str(j)])
            if str(i+1)+'-'+str(j+1) in patch_id_5x:
                start.append(patch_id_5x[str(i)+'-'+str(j)])
                end.append(patch_id_5x[str(i+1)+'-'+str(j+1)])
            if str(i-1)+'-'+str(j+1) in patch_id_5x:
                start.append(patch_id_5x[str(i)+'-'+str(j)])
                end.append(patch_id_5x[str(i-1)+'-'+str(j+1)])
            if str(i+1)+'-'+str(j-1) in patch_id_5x:
                start.append(patch_id_5x[str(i)+'-'+str(j)])
                end.append(patch_id_5x[str(i+1)+'-'+str(j-1)])
            if str(i-1)+'-'+str(j-1) in patch_id_5x:
                start.append(patch_id_5x[str(i)+'-'+str(j)])
                end.append(patch_id_5x[str(i-1)+'-'+str(j-1)])
                
    #10x resolution edge between nodes
    for x in patch_id:
        if len(x.split('-'))==2 and x!='-1':
#             print(x)
            i = int(x.split('-')[0])
            j = int(x.split('-')[1])
#             print(i,j)
            if str(i)+'-'+str(j+1) in patch_id:
                start.append(patch_id[str(i)+'-'+str(j)])
                end.append(patch_id[str(i)+'-'+str(j+1)])
            if str(i)+'-'+str(j-1) in patch_id:
                start.append(patch_id[str(i)+'-'+str(j)])
                end.append(patch_id[str(i)+'-'+str(j-1)])
            if str(i+1)+'-'+str(j) in patch_id:
                start.append(patch_id[str(i)+'-'+str(j)])
                end.append(patch_id[str(i+1)+'-'+str(j)])
            if str(i-1)+'-'+str(j) in patch_id:
                start.append(patch_id[str(i)+'-'+str(j)])
                end.append(patch_id[str(i-1)+'-'+str(j)])
            if str(i+1)+'-'+str(j+1) in patch_id:
                start.append(patch_id[str(i)+'-'+str(j)])
                end.append(patch_id[str(i+1)+'-'+str(j+1)])
            if str(i-1)+'-'+str(j+1) in patch_id:
                start.append(patch_id[str(i)+'-'+str(j)])
                end.append(patch_id[str(i-1)+'-'+str(j+1)])
            if str(i+1)+'-'+str(j-1) in patch_id:
                start.append(patch_id[str(i)+'-'+str(j)])
                end.append(patch_id[str(i+1)+'-'+str(j-1)])
            if str(i-1)+'-'+str(j-1) in patch_id:
                start.append(patch_id[str(i)+'-'+str(j)])
                end.append(patch_id[str(i-1)+'-'+str(j-1)])               
                
                  
    
#     print(start)
#     print(end)
    return [start,end]  

In [16]:
get_edge_index_2('TCGA-LN-A4MR')[0][:20],get_edge_index_2('TCGA-LN-A4MR')[1][:20]

([1, 0, 1, 300, 1, 261, 2, 0, 2, 364, 2, 292, 2, 557, 2, 201, 3, 0, 3, 137],
 [0, 1, 300, 1, 261, 1, 0, 2, 364, 2, 292, 2, 557, 2, 201, 2, 0, 3, 137, 3])

In [17]:
all_node_type = {}
for x in patients:
    t = []   
    for z in t_all_feature[x]:
        if z == '-1':
            t.append(0)
    for z in t_all_feature[x]:            
        if len(z.split('-')) == 6:
            t.append(1)
    for z in t_all_feature[x]:            
        if len(z.split('-')) == 2 and z != '-1':
            t.append(2)        
      
    all_node_type[x] = t

In [18]:
"""
Thumbnail: 0
5x: 1
10x: 2
"""
all_node_type['TCGA-LN-A4MR']

[0,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,


In [19]:
tree = {}
for p_id in patients:
    
    t_tree = np.array([-2]*len(all_node_type[p_id]))
    t_tree[np.where(np.array(all_node_type[p_id])==0)] = -1
    t_tree[np.where(np.array(all_node_type[p_id])==1)] = np.where(np.array(all_node_type[p_id])==0)[0][0]
#     print(t_tree)
    
    patch_id = {}
    i=0
    for x in t_all_feature[p_id]:
        patch_id[x.split('.')[0]] = i
        i+=1
#     print(patch_id)

    for x in patch_id:
        if len(x.split('-'))==6:
            if x.split('-')[0]+'-'+x.split('-')[2] in patch_id:
                t_tree[patch_id[x.split('-')[0]+'-'+x.split('-')[2]]] =  patch_id[x]           
            if x.split('-')[1]+'-'+x.split('-')[2] in patch_id:                
                t_tree[patch_id[x.split('-')[1]+'-'+x.split('-')[2]]] =  patch_id[x]              
            if x.split('-')[0]+'-'+x.split('-')[3] in patch_id:            
                t_tree[patch_id[x.split('-')[0]+'-'+x.split('-')[3]]] =  patch_id[x]            
            if x.split('-')[1]+'-'+x.split('-')[3] in patch_id:            
                t_tree[patch_id[x.split('-')[1]+'-'+x.split('-')[3]]] =  patch_id[x]   
    

    tree[p_id] = t_tree
#     break

In [20]:
tree['TCGA-LN-A4MR']

array([ -1,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,  42,  93,  93,  32,  34,   3,  80,  33, 119,   4,  85,
       119,  26,  42,  83, 107, 120,  60, 123,  17,   4, 122,  28, 125,
        76,  18,  52, 107, 107,  57,  56, 101,  36, 122,  87,  51,  81,
        64,  17,  56,  98,  82,  86,  82,  89, 120,  44,  82,  1

In [21]:
x_y = {}
for x in patients:
    dd = []
    for z in t_all_feature[x]:
        if z == '-1':
            dd.append((0,0))
            
    for z in t_all_feature[x]:            
        if len(z.split('-')) == 6:
            dd.append((float(z.split('-')[-2]),float(z.split('-')[-1].split('.')[0])))
        
    for z in t_all_feature[x]:            
        if len(z.split('-')) == 2 and z != '-1':
            dd.append((float(z.split('-')[0]),float(z.split('-')[1].split('.')[0])))
        
    x_y[x] = dd


In [22]:
max_x_y_5x = {}
max_x_y_10x = {}
for p_id in patients:
    x=[]
    y=[]
    for z in np.array(x_y[p_id])[np.where(np.array(all_node_type[p_id])==1)]:
        x.append(z[0])
        y.append(z[1])
    max_x_y_5x[p_id] = [np.max(np.array(x)),np.max(np.array(y))]
    
    x=[]
    y=[]
    for z in np.array(x_y[p_id])[np.where(np.array(all_node_type[p_id])==2)]:
        x.append(z[0])
        y.append(z[1])
    max_x_y_10x[p_id] = [np.max(np.array(x)),np.max(np.array(y))]    
    

In [23]:
x_y = {}
for x in patients:
    dd = []
    for z in t_all_feature[x]:
        if z == '-1':
            dd.append((0,0))
            
    for z in t_all_feature[x]:            
        if len(z.split('-')) == 6:
            dd.append((float(z.split('-')[-2])/max_x_y_5x[x][0],float(z.split('-')[-1].split('.')[0])/max_x_y_5x[x][1]))
        
    for z in t_all_feature[x]:            
        if len(z.split('-')) == 2 and z != '-1':
            dd.append((float(z.split('-')[0])/max_x_y_10x[x][0],float(z.split('-')[1].split('.')[0])/max_x_y_10x[x][1]))
        
    x_y[x] = dd


In [24]:
#Normalize
x_y['TCGA-LN-A4MR']

[(0, 0),
 (0.9444444444444444, 0.9333333333333333),
 (0.05555555555555555, 0.2),
 (0.7777777777777778, 0.8666666666666667),
 (0.4444444444444444, 0.5333333333333333),
 (0.16666666666666666, 0.13333333333333333),
 (0.5, 0.4),
 (0.7777777777777778, 0.6666666666666666),
 (0.2777777777777778, 0.13333333333333333),
 (0.1111111111111111, 0.3333333333333333),
 (0.2222222222222222, 0.26666666666666666),
 (0.2222222222222222, 0.2),
 (0.8888888888888888, 0.9333333333333333),
 (0.4444444444444444, 0.6666666666666666),
 (0.5555555555555556, 0.7333333333333333),
 (0.6111111111111112, 0.7333333333333333),
 (0.2222222222222222, 0.6),
 (0.9444444444444444, 0.8666666666666667),
 (0.7777777777777778, 0.7333333333333333),
 (0.16666666666666666, 0.4),
 (0.6666666666666666, 0.8),
 (0.6111111111111112, 0.6666666666666666),
 (1.0, 0.8666666666666667),
 (0.9444444444444444, 0.7333333333333333),
 (0.3888888888888889, 0.4666666666666667),
 (0.5, 0.8666666666666667),
 (0.1111111111111111, 0.26666666666666666),
 

In [25]:

all_data = {}
for id in patients:
    print(id)
    node_attr=torch.tensor(all_feature[id],dtype=torch.float)
    edge_index_tree_8nb = torch.tensor(get_edge_index_2(id),dtype=torch.long) 
    batch = torch.tensor([0 for i in range(len(node_attr))])
    node_type = torch.tensor(all_node_type[id])
    node_tree = torch.tensor(tree[id])
    x_y_index = torch.tensor(x_y[id])
    data_id = id 
    data=Data(x=node_attr,edge_index_tree_8nb=edge_index_tree_8nb,data_id=data_id,batch =batch,node_type=node_type,node_tree=node_tree,x_y_index=x_y_index) 
    all_data[id] = data
    print(data)
    

TCGA-L5-A4OR
Data(batch=[1560], data_id="TCGA-L5-A4OR", edge_index_tree_8nb=[2, 14392], node_tree=[1560], node_type=[1560], x=[1560, 1024], x_y_index=[1560, 2])
TCGA-IG-A3YA
Data(batch=[1301], data_id="TCGA-IG-A3YA", edge_index_tree_8nb=[2, 12066], node_tree=[1301], node_type=[1301], x=[1301, 1024], x_y_index=[1301, 2])
TCGA-JY-A93D
Data(batch=[1303], data_id="TCGA-JY-A93D", edge_index_tree_8nb=[2, 12196], node_tree=[1303], node_type=[1303], x=[1303, 1024], x_y_index=[1303, 2])
TCGA-LN-A7HX
Data(batch=[781], data_id="TCGA-LN-A7HX", edge_index_tree_8nb=[2, 7266], node_tree=[781], node_type=[781], x=[781, 1024], x_y_index=[781, 2])
TCGA-JY-A6FE
Data(batch=[1526], data_id="TCGA-JY-A6FE", edge_index_tree_8nb=[2, 14250], node_tree=[1526], node_type=[1526], x=[1526, 1024], x_y_index=[1526, 2])
TCGA-JY-A93F
Data(batch=[1190], data_id="TCGA-JY-A93F", edge_index_tree_8nb=[2, 11040], node_tree=[1190], node_type=[1190], x=[1190, 1024], x_y_index=[1190, 2])
TCGA-Z6-A9VB
Data(batch=[513], data_id="

Data(batch=[2529], data_id="TCGA-JY-A6FG", edge_index_tree_8nb=[2, 23852], node_tree=[2529], node_type=[2529], x=[2529, 1024], x_y_index=[2529, 2])
TCGA-L5-A4OS
Data(batch=[1381], data_id="TCGA-L5-A4OS", edge_index_tree_8nb=[2, 12984], node_tree=[1381], node_type=[1381], x=[1381, 1024], x_y_index=[1381, 2])
TCGA-VR-A8ER
Data(batch=[1757], data_id="TCGA-VR-A8ER", edge_index_tree_8nb=[2, 16720], node_tree=[1757], node_type=[1757], x=[1757, 1024], x_y_index=[1757, 2])
TCGA-LN-A49N
Data(batch=[682], data_id="TCGA-LN-A49N", edge_index_tree_8nb=[2, 6206], node_tree=[682], node_type=[682], x=[682, 1024], x_y_index=[682, 2])
TCGA-L5-A4OT
Data(batch=[2526], data_id="TCGA-L5-A4OT", edge_index_tree_8nb=[2, 24372], node_tree=[2526], node_type=[2526], x=[2526, 1024], x_y_index=[2526, 2])
TCGA-LN-A49X
Data(batch=[658], data_id="TCGA-LN-A49X", edge_index_tree_8nb=[2, 6046], node_tree=[658], node_type=[658], x=[658, 1024], x_y_index=[658, 2])
TCGA-V5-A7RE
Data(batch=[26], data_id="TCGA-V5-A7RE", edge_

Data(batch=[886], data_id="TCGA-L7-A6VZ", edge_index_tree_8nb=[2, 8008], node_tree=[886], node_type=[886], x=[886, 1024], x_y_index=[886, 2])
TCGA-IG-A3QL
Data(batch=[221], data_id="TCGA-IG-A3QL", edge_index_tree_8nb=[2, 1910], node_tree=[221], node_type=[221], x=[221, 1024], x_y_index=[221, 2])
TCGA-VR-AA4G
Data(batch=[1290], data_id="TCGA-VR-AA4G", edge_index_tree_8nb=[2, 11924], node_tree=[1290], node_type=[1290], x=[1290, 1024], x_y_index=[1290, 2])
TCGA-LN-A8HZ
Data(batch=[453], data_id="TCGA-LN-A8HZ", edge_index_tree_8nb=[2, 4080], node_tree=[453], node_type=[453], x=[453, 1024], x_y_index=[453, 2])
TCGA-IG-A5S3
Data(batch=[621], data_id="TCGA-IG-A5S3", edge_index_tree_8nb=[2, 5588], node_tree=[621], node_type=[621], x=[621, 1024], x_y_index=[621, 2])
TCGA-L5-A4OU
Data(batch=[1439], data_id="TCGA-L5-A4OU", edge_index_tree_8nb=[2, 13402], node_tree=[1439], node_type=[1439], x=[1439, 1024], x_y_index=[1439, 2])
TCGA-LN-A7HW
Data(batch=[514], data_id="TCGA-LN-A7HW", edge_index_tree_

In [ ]:
# joblib.dump(all_data,'esca_5x10x_tree_8nb_gnn_data.pkl')